#!/usr/bin/env python3
"""Generate the AOIS curriculum reading order and next/previous footers."""

from __future__ import annotations

import os
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CURRICULUM = ROOT / "curriculum"
READING_ORDER = CURRICULUM / "READING-ORDER.md"

NAV_START = "<!-- AOIS-NAV-START -->"
NAV_END = "<!-- AOIS-NAV-END -->"
START_HERE_FILE = "00-start-here.md"
LEGACY_START_HERE_FILE = "_startHere.md"
PHASE_START_DIR = "00-phase-start"
PHASE_END_DIR = "zz-phase-end"
PHASE_CONTENTS_FILE = "01-contents.md"
PHASE_INTRODUCTION_FILE = "02-introduction.md"
CHAPTER_FILE_STEPS = [
    ("01-contents.md", "quick map for the chapter"),
    ("02-introduction.md", "what the chapter is about"),
    ("03-notes.md", "the main lesson"),
    ("04-lab.md", "the hands-on work"),
    ("05-runbook.md", "recovery steps when stuck"),
    ("06-failure-story.md", "what breaks in the real world"),
    ("07-benchmark.md", "what to measure"),
    ("08-summary-notes.md", "what to retain"),
    ("09-looking-forward.md", "what carries forward"),
    ("10-next-version-bridge.md", "how to enter the next chapter"),
]

PHASE_FILE_ORDER = [
    f"{PHASE_START_DIR}/{START_HERE_FILE}",
    f"{PHASE_START_DIR}/{PHASE_CONTENTS_FILE}",
    f"{PHASE_START_DIR}/{PHASE_INTRODUCTION_FILE}",
]

VERSION_FILE_ORDER = [START_HERE_FILE] + [
    filename for filename, _description in CHAPTER_FILE_STEPS
]

PHASE_END_FILE_ORDER = [
    f"{PHASE_END_DIR}/00-phase-capstone.md",
    f"{PHASE_END_DIR}/01-looking-forward.md",
]

REFERENCE_DOCS = [
    "TABLE-OF-CONTENTS.md",
    "INSTITUTION-INDEX.md",
    "SYLLABUS.md",
    "FULL-PROGRAM-MAP.md",
    "MASTER-CURRICULUM.md",
    "LEARNING-OPERATING-MODEL.md",
    "STUDY-PACING.md",
    "VERSION-STANDARD.md",
    "QUALITY-GATES.md",
    "CODEX-GUIDE-MODE.md",
    "SOURCE-CURRENCY.md",
    "REPO-BLUEPRINT.md",
    "CONTINUITY.md",
    "CORPUS-STATUS.md",
    "EVALUATION-CARD.md",
    "CORPUS-AUTHORING-PLAN.md",
]


def phase_key(path: Path) -> int:
    match = re.fullmatch(r"(?:(\d+)-)?phase(\d+)", path.name)
    return int(match.group(2)) if match else 9999


def phase_dirs() -> list[Path]:
    return sorted(
        [
            item
            for item in CURRICULUM.iterdir()
            if item.is_dir() and phase_key(item) != 9999
        ],
        key=phase_key,
    )


def version_key(path: Path) -> tuple[int, ...]:
    if not path.name.startswith("v"):
        return (9999,)
    parts: list[int] = []
    for part in path.name[1:].split("."):
        parts.append(int(part) if part.isdigit() else 9999)
    return tuple(parts)


def rel(path: Path, start: Path = CURRICULUM) -> str:
    return path.relative_to(start).as_posix()


def title_for(path: Path) -> str:
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return rel(path)


def link_between(source: Path, target: Path, label: str) -> str:
    href = os.path.relpath(target, start=source.parent)
    return f"[{label}]({Path(href).as_posix()})"


def add_existing(order: list[Path], path: Path) -> None:
    if path.exists() and path not in order:
        order.append(path)


def write_start_here_files() -> None:
    """Write a generated entry file for every version/chapter directory."""

    version_dirs = sorted(
        [
            item
            for phase in phase_dirs()
            if phase.is_dir()
            for item in phase.iterdir()
            if item.is_dir() and item.name.startswith("v")
        ],
        key=lambda path: (phase_key(path.parent), version_key(path)),
    )

    for version in version_dirs:
        legacy_path = version / LEGACY_START_HERE_FILE
        if legacy_path.exists():
            legacy_path.unlink()

        lines = [
            f"# {version.name} Start Here",
            "",
            "Use this file first when opening this chapter.",
            "",
            "## Chapter Reading Path",
            "",
        ]

        step_number = 1
        for filename, description in CHAPTER_FILE_STEPS:
            path = version / filename
            if path.exists():
                lines.append(f"{step_number}. [{filename}]({filename}) - {description}")
                step_number += 1

        lines.extend(
            [
                "",
                "## How To Move",
                "",
                "After this page, use the `Next` link at the bottom of each document.",
                "Use the `Previous` link when you need to review the document before it.",
                "",
                "<!-- This file is generated by scripts/generate_curriculum_navigation.py. -->",
            ]
        )

        (version / START_HERE_FILE).write_text(
            "\n".join(lines).rstrip() + "\n",
            encoding="utf-8",
        )


def write_phase_start_files() -> None:
    """Write a generated entry file for every phase directory."""

    for phase in phase_dirs():
        phase_number = phase_key(phase)
        start_dir = phase / PHASE_START_DIR
        start_dir.mkdir(exist_ok=True)

        lines = [
            f"# Phase {phase_number} Start Here",
            "",
            "Use this file first when opening this phase.",
            "",
            "## Phase Reading Path",
            "",
        ]

        steps = [
            (PHASE_CONTENTS_FILE, "quick map for the phase"),
            (PHASE_INTRODUCTION_FILE, "phase introduction before the versions"),
        ]
        step_number = 1
        for filename, description in steps:
            path = start_dir / filename
            if path.exists():
                lines.append(f"{step_number}. [{filename}]({filename}) - {description}")
                step_number += 1

        lines.extend(
            [
                "",
                "## How To Move",
                "",
                "After this page, use the `Next` link at the bottom of each document.",
                "The next documents introduce the phase before the first version folder.",
                "",
                "<!-- This file is generated by scripts/generate_curriculum_navigation.py. -->",
            ]
        )

        (start_dir / START_HERE_FILE).write_text(
            "\n".join(lines).rstrip() + "\n",
            encoding="utf-8",
        )


def build_reading_order() -> list[Path]:
    order: list[Path] = []

    if READING_ORDER.exists():
        order.append(READING_ORDER)

    for phase in phase_dirs():
        if not phase.is_dir():
            continue

        for filename in PHASE_FILE_ORDER:
            add_existing(order, phase / filename)

        version_dirs = [
            item for item in phase.iterdir() if item.is_dir() and item.name.startswith("v")
        ]
        for version in sorted(version_dirs, key=version_key):
            for filename in VERSION_FILE_ORDER:
                add_existing(order, version / filename)
            for extra in sorted(version.glob("*.md")):
                add_existing(order, extra)

        for filename in PHASE_END_FILE_ORDER:
            add_existing(order, phase / filename)
        for extra in sorted(phase.glob("*.md")):
            add_existing(order, extra)

    for filename in REFERENCE_DOCS:
        add_existing(order, CURRICULUM / filename)

    for extra in sorted(CURRICULUM.rglob("*.md")):
        add_existing(order, extra)

    return order


def write_reading_order() -> None:
    phases = phase_dirs()

    lines: list[str] = [
        "# AOIS Reading Order",
        "",
        "Start here when you want to read the portfolio instead of browsing folders.",
        "",
        "## How To Read A Version",
        "",
        "Inside each version, use this order:",
        "",
        "1. `00-start-here.md` - chapter entry point",
        "2. `01-contents.md` - quick map for the version",
        "3. `02-introduction.md` - what the version is about",
        "4. `03-notes.md` - the main lesson",
        "5. `04-lab.md` - the hands-on work",
        "6. `05-runbook.md` - how to recover when stuck",
        "7. `06-failure-story.md` - what breaks in the real world",
        "8. `07-benchmark.md` - what to measure",
        "9. `08-summary-notes.md` - what to retain",
        "10. `09-looking-forward.md` - what carries forward",
        "11. `10-next-version-bridge.md` - how to enter the next version",
        "",
        "Every curriculum Markdown file ends with a navigation block linking back to this file plus the previous and next document in the reading path.",
        "",
        "## Start Here",
        "",
        "Begin at [Phase 0 Start Here](00-phase0/00-phase-start/00-start-here.md), then keep using the `Next` link at the bottom of each page.",
        "",
        "## Full Learner Path",
        "",
    ]

    for phase in phases:
        phase_label = f"Phase {phase_key(phase)}"
        lines.extend([f"### {phase_label}", ""])

        for filename in PHASE_FILE_ORDER:
            path = phase / filename
            if path.exists():
                lines.append(f"- [{title_for(path)}]({rel(path)})")

        version_dirs = [
            item for item in phase.iterdir() if item.is_dir() and item.name.startswith("v")
        ]
        for version in sorted(version_dirs, key=version_key):
            lines.append(f"- {version.name}")
            for filename in VERSION_FILE_ORDER:
                path = version / filename
                if path.exists():
                    lines.append(f"  - [{title_for(path)}]({rel(path)})")

        for filename in PHASE_END_FILE_ORDER:
            path = phase / filename
            if path.exists():
                lines.append(f"- [{title_for(path)}]({rel(path)})")
        lines.append("")

    lines.extend(
        [
            "## Reference Documents",
            "",
            "These are useful for orientation, review standards, pacing, and operating rules. They are linked after the learner path in the generated previous/next chain.",
            "",
        ]
    )
    for filename in REFERENCE_DOCS:
        path = CURRICULUM / filename
        if path.exists():
            lines.append(f"- [{title_for(path)}]({rel(path)})")

    READING_ORDER.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def strip_nav(text: str) -> str:
    pattern = re.compile(
        rf"\n*{re.escape(NAV_START)}.*?{re.escape(NAV_END)}\s*\Z",
        flags=re.DOTALL,
    )
    return pattern.sub("", text).rstrip()


def write_footers(order: list[Path]) -> None:
    titles = {path: title_for(path) for path in order}

    for index, path in enumerate(order):
        body = strip_nav(path.read_text(encoding="utf-8"))
        previous_path = order[index - 1] if index > 0 else None
        next_path = order[index + 1] if index + 1 < len(order) else None

        nav = [
            "",
            NAV_START,
            "---",
            "",
            "## Navigation",
            "",
            f"- Reading order: {link_between(path, READING_ORDER, 'AOIS Reading Order')}",
        ]
        if previous_path:
            nav.append(
                f"- Previous: {link_between(path, previous_path, titles[previous_path])}"
            )
        if next_path:
            nav.append(f"- Next: {link_between(path, next_path, titles[next_path])}")
        nav.append(NAV_END)

        path.write_text(body + "\n".join(nav) + "\n", encoding="utf-8")


def main() -> None:
    write_phase_start_files()
    write_start_here_files()
    write_reading_order()
    order = build_reading_order()
    write_footers(order)
    print(f"generated_curriculum_navigation {len(order)} files")


if __name__ == "__main__":
    main()
