apiVersion: v1
kind: ResourceQuota
metadata:
  name: aois-p-quota
  namespace: aois-p
spec:
  hard:
    requests.cpu: "250m"
    requests.memory: "256Mi"
    limits.cpu: "500m"
    limits.memory: "512Mi"
    pods: "2"
