apiVersion: v1
kind: ServiceAccount
metadata:
  name: aois-p-api
  namespace: aois-p
  labels:
    app.kubernetes.io/name: aois-p-api
    app.kubernetes.io/part-of: aois-portfolio
automountServiceAccountToken: false
