apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aois
  namespace: argocd
  labels:
    app.kubernetes.io/name: aois
    app.kubernetes.io/part-of: aois-portfolio
    aois.dev/owner: portfolio
spec:
  project: default
  source:
    repoURL: https://github.com/kolinzking/aois-portfolio.git
    targetRevision: main
    path: charts/aois
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: aois
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - PruneLast=true
  revisionHistoryLimit: 3
